export const BOOKING_STATUS_FAIL = "BOOKING_STATUS_FAIL";
export const BOOKING_STATUS_REQUEST = "BOOKING_STATUS_REQUEST";
export const BOOKING_STATUS_SUCCESS = "BOOKING_STATUS_SUCCESS";

export const USER_BOOKINGS_FAIL = "USER_BOOKINGS_FAIL";
export const USER_BOOKINGS_REQUEST = "USER_BOOKINGS_REQUEST";
export const USER_BOOKINGS_SUCCESS = "USER_BOOKINGS_SUCCESS";

export const CANCEL_BOOKING_FAIL = "CANCEL_BOOKING_FAIL";
export const CANCEL_BOOKING_REQUEST = "CANCEL_BOOKING_REQUEST";
export const CANCEL_BOOKING_SUCCESS = "CANCEL_BOOKING_SUCCESS";
