export const PRO_LIST_REQUEST = "PRO_LIST_REQUEST";
export const PRO_LIST_SUCCESS = "PRO_LIST_SUCCESS";
export const PRO_LIST_FAIL = "PRO_LIST_FAIL";

export const PRO_DETAILS_REQUEST = "PRO_DETAILS_REQUEST";
export const PRO_DETAILS_SUCCESS = "PRO_DETAILS_SUCCESS";
export const PRO_DETAILS_FAIL = "PRO_DETAILS_FAIL";
