const professionals = [
  {
    __id: "1",
    name: "hero",
    image: "/image/hero.jpg",
    description: "hello i am hero",
    location: "patan",
    category: "plumber",
    rating: 4.5,
    numReviews: 12,
  },
  {
    __id: "2",
    name: "ram",
    image: "/image/ram.jpg",
    description: "hello i am ram",
    location: "bhaktapur",
    category: "electrician",
    rating: 4,
    numReviews: 19,
  },
  {
    __id: "3",
    name: "shyam",
    image: "/image/shyam.jpg",
    description: "hello i am shyam",
    location: "kathmandu",
    category: "carpenter",
    rating: 3,
    numReviews: 20,
  },
  {
    __id: "4",
    name: "sita",
    image: "/image/sita.png",
    description: "hello i am sita",
    location: "patan",
    category: "gardener",
    rating: 5,
    numReviews: 6,
  },
  {
    __id: "5",
    name: "hari",
    image: "/image/hari.jpg",
    description: "hello i am hari",
    location: "new york",
    category: "plumber",
    rating: 4,
    numReviews: 12,
  },
];
export default professionals;
